# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bccbeae760af2ccdbd8b549816cac9fe742b16ff67c30c84847ca82f98e031aa38512d8f1091315b7a7c20017ff298e29bfa6f0eca3820c881a6db0351e9e0f

test:
  secret_key_base: 18e4ad61c763ba90d6dbb30aeea0fafbe2141cad4be8fb9731090d8e461911d04b12c39dbf8ac4b2df5af4266377b88c1223604cb53f3ade9e38d35571360395

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
